### ISSUE TITLE
The GMVAE shows better clustering performance than non-neural machine learning methods?

### ISSUE THREAD

**Issue by bemoregt** [Nat-D/GMVAE#1]
Hi, @Nat-D 

The GMVAE shows better clustering performance than other "old machine learning methods"?

"old machine learning"= knn, kmeans, cmeans, kohonen, t-sne, neuarl gas, etc ...

Thanks in advances.

**Comment by Nat-D** [comment]
Hi @bemoregt ,

I haven’t experiments with other methods and other dataset than in the paper.
However, there are MNIST results where people report finding of their methods compare with baseline such as k-means. For example, DEC (https://arxiv.org/pdf/1511.06335.pdf). In table 2, their experiment shows that k-mean is rather a bad method to do clustering on MNIST.

My intuition is that GMVAE is suited for higher dimensional input. For low dimensional dataset, like 2D toy dataset, GMVAE might be an overkill.  Another disadvantage of GMVAE is that you need to specify number of clusters and the computation scale linearly with the number of clusters. 

Best,
Nat

**Comment by bemoregt** [comment]
Thanks. Nat

Hmmmm ...

2017-06-26 20:42 GMT+09:00 Nat Dilokthanakul <notifications@github.com>:
