### ISSUE TITLE
I have met this error at displaying spiral grapics.

### ISSUE THREAD

**Issue by bemoregt** [Nat-D/GMVAE#2]
Hi, @Nat-D 

I have met this error at displaying spiral grapics.
----------------------------------------------
ubuntu@ubuntu:~/GMVAE/plot$ python plot_latent.py 
Traceback (most recent call last):
  File "plot_latent.py", line 2, in <module>
    import torchfile
ImportError: No module named torchfile
ubuntu@ubuntu:~/GMVAE/plot$ 
ubuntu@ubuntu:~/GMVAE/plot$ luarocks install torchfile

Error: No results matching query were found.

**Comment by Nat-D** [comment]
Hi Hi,

Can you try 'pip install torchfile' ?
It is a python module.

**Comment by bemoregt** [comment]
Thanks, It works.

2017-06-26 20:32 GMT+09:00 Nat Dilokthanakul <notifications@github.com>:
