### ISSUE TITLE
Does not work for nMC > 1

### ISSUE THREAD

**Issue by agjayant** [Nat-D/GMVAE#3]
@Nat-D 
I was trying to reproduce the results of this work. The code(version2, svhn) works fine in the default setting.
But, as I try to change the value of the number of Monte-Carlo samples(opt.nMC) by setting the flag in _run.sh_ , it throws the following error:

/home/jayant/torch/install/share/lua/5.1/nn/MV.lua:35: inputs must contain the same number of minibatches
stack traceback:
	[C]: in function 'assert'
	/home/jayant/torch/install/share/lua/5.1/nn/MV.lua:35: in function 'func'
	...e/jayant/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	...e/jayant/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
	main.lua:226: in function 'opfunc'
	/home/jayant/torch/install/share/lua/5.1/optim/adam.lua:37: in function </home/jayant/torch/install/share/lua/5.1/optim/adam.lua:24>
	main.lua:312: in main chunk
	[C]: in function 'dofile'
	...yant/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

**Comment by Nat-D** [comment]
Sorry I'm busy with something else and I'm no longer maintain this repo.
Thanks for the fix!

**Comment by agjayant** [comment]
Hi @Nat-D . The code(version2) does not seem (even before #4 ) to reproduce the same results(for 'mnist') as shown in the paper. Could you please just check all the hyper-parameters? 
-Thanks
